# Generated by Django 4.1.5 on 2023-02-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategories',
            name='products',
            field=models.ManyToManyField(related_name='categories', to='pages.posts'),
        ),
        migrations.AlterField(
            model_name='prodcategories',
            name='products',
            field=models.ManyToManyField(related_name='categories', to='pages.products'),
        ),
    ]
